import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import UserProfileImage from "./components/UserProfileImage";
import { getCurrentUser } from "./api/auth/[...nextauth]/lib/session";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-indigo-600 h-14 px-5 pr-8 py-1.5 flex items-center">
          <nav className="flex flex-row justify-between w-full items-center">
            <div className="text-white">Threads Next App</div>
            <UserProfileImage user={user} />
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
